//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rails.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIJN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LIJN()
        {
            this.TRAM_LIJN = new HashSet<TRAM_LIJN>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Remise_ID { get; set; }
        public Nullable<int> Nummer { get; set; }
        public bool ConducteurRijdtMee { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRAM_LIJN> TRAM_LIJN { get; set; }
        public virtual REMISE REMISE { get; set; }
    }
}
