//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rails.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDEWERKER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEDEWERKER()
        {
            this.TRAM_ONDERHOUD = new HashSet<TRAM_ONDERHOUD>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Functie_ID { get; set; }
        public string Naam { get; set; }
    
        public virtual FUNCTIE FUNCTIE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRAM_ONDERHOUD> TRAM_ONDERHOUD { get; set; }
    }
}
