//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rails.App_Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RailsOracleEntities : DbContext
    {
        public RailsOracleEntities()
            : base("name=RailsOracleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FUNCTIE> FUNCTIE { get; set; }
        public virtual DbSet<LIJN> LIJN { get; set; }
        public virtual DbSet<MEDEWERKER> MEDEWERKER { get; set; }
        public virtual DbSet<RECHT> RECHT { get; set; }
        public virtual DbSet<REMISE> REMISE { get; set; }
        public virtual DbSet<RESERVERING> RESERVERING { get; set; }
        public virtual DbSet<SECTOR> SECTOR { get; set; }
        public virtual DbSet<SPOOR> SPOOR { get; set; }
        public virtual DbSet<TRAM> TRAM { get; set; }
        public virtual DbSet<TRAM_LIJN> TRAM_LIJN { get; set; }
        public virtual DbSet<TRAM_ONDERHOUD> TRAM_ONDERHOUD { get; set; }
        public virtual DbSet<TRAMTYPE> TRAMTYPE { get; set; }
        public virtual DbSet<TRANSFER> TRANSFER { get; set; }
        public virtual DbSet<VERBINDING> VERBINDING { get; set; }
    }
}
