//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rails.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVERING
    {
        public int Reservering_ID { get; set; }
        public Nullable<int> Tram_ID { get; set; }
        public Nullable<int> Spoor_ID { get; set; }
    
        public virtual SPOOR SPOOR { get; set; }
        public virtual TRAM TRAM { get; set; }
    }
}
