//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rails.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SECTOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SECTOR()
        {
            this.VERBINDING = new HashSet<VERBINDING>();
            this.VERBINDING1 = new HashSet<VERBINDING>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Spoor_ID { get; set; }
        public Nullable<int> Tram_ID { get; set; }
        public Nullable<int> Nummer { get; set; }
        public bool Beschikbaar { get; set; }
        public bool Blokkade { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VERBINDING> VERBINDING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VERBINDING> VERBINDING1 { get; set; }
        public virtual SPOOR SPOOR { get; set; }
    }
}
