//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rails.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPOOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SPOOR()
        {
            this.RESERVERING = new HashSet<RESERVERING>();
            this.SECTOR = new HashSet<SECTOR>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Remise_ID { get; set; }
        public Nullable<int> Nummer { get; set; }
        public Nullable<int> Lengte { get; set; }
        public bool Beschikbaar { get; set; }
        public bool InUitRijspoor { get; set; }
    
        public virtual REMISE REMISE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESERVERING> RESERVERING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SECTOR> SECTOR { get; set; }
    }
}
