//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rails.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAM_ONDERHOUD
    {
        public int ID { get; set; }
        public Nullable<int> Medewerker_ID { get; set; }
        public Nullable<int> Tram_ID { get; set; }
        public Nullable<System.DateTime> DatumTijdstip { get; set; }
        public Nullable<System.DateTime> BeschikbaarDatum { get; set; }
        public string TypeOnderhoud { get; set; }
    
        public virtual MEDEWERKER MEDEWERKER { get; set; }
        public virtual TRAM TRAM { get; set; }
    }
}
