//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rails.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAM_LIJN
    {
        public int TL_ID { get; set; }
        public int Tram_ID { get; set; }
        public Nullable<int> Lijn_ID { get; set; }
        public bool Gebonden { get; set; }
    
        public virtual LIJN LIJN { get; set; }
        public virtual TRAM TRAM { get; set; }
    }
}
