//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rails.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRAM()
        {
            this.RESERVERING = new HashSet<RESERVERING>();
            this.TRAM_LIJN = new HashSet<TRAM_LIJN>();
            this.TRAM_ONDERHOUD = new HashSet<TRAM_ONDERHOUD>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Remise_ID_Standplaats { get; set; }
        public Nullable<int> Tramtype_ID { get; set; }
        public Nullable<int> Nummer { get; set; }
        public Nullable<int> Lengte { get; set; }
        public string Status { get; set; }
        public bool Vervuild { get; set; }
        public bool Defect { get; set; }
        public bool ConducteurGeschikt { get; set; }
        public bool Beschikbaar { get; set; }
    
        public virtual REMISE REMISE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESERVERING> RESERVERING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRAM_LIJN> TRAM_LIJN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRAM_ONDERHOUD> TRAM_ONDERHOUD { get; set; }
        public virtual TRAMTYPE TRAMTYPE { get; set; }
    }
}
