//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rails.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSFER
    {
        public int Remise_ID_Van { get; set; }
        public int Remise_ID_Naar { get; set; }
        public Nullable<int> Aantal { get; set; }
    
        public virtual REMISE REMISE { get; set; }
        public virtual REMISE REMISE1 { get; set; }
    }
}
